name: pager
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.2.0
  - anyjson=0.3.3
  - argon2_cffi=18.1.0
  - arrow=0.12.1
  - asn1crypto=0.24.0
  - attrs=18.1.0
  - babel=2.5.3
  - backcall=0.1.0
  - beautifulsoup4=4.6.0
  - blas=1.1
  - bleach=2.1.3
  - blosc=1.14.0
  - boto3=1.7.14
  - botocore=1.10.15
  - bzip2=1.0.6
  - ca-certificates=2018.4.16
  - cartopy=0.16.0
  - certifi=2018.4.16
  - cffi=1.11.5
  - chardet=3.0.4
  - click=6.7
  - click-plugins=1.0.3
  - cligj=0.4.0
  - colour=0.1.5
  - coverage=4.5.1
  - cryptography=2.2.1
  - curl=7.59.0
  - cycler=0.10.0
  - cython=0.28.2
  - decorator=4.3.0
  - descartes=1.1.0
  - django=2.0.5
  - docutils=0.14
  - entrypoints=0.2.3
  - et_xmlfile=1.0.1
  - expat=2.1.0
  - fiona=1.7.11
  - flake8=3.5.0
  - fontconfig=2.12.1
  - freetype=2.6.3
  - freexl=1.0.5
  - furl=1.0.1
  - gdal=2.1.3
  - geos=3.6.2
  - giflib=5.1.4
  - gmp=6.1.2
  - h5py=2.7.1
  - hdf4=4.2.13
  - hdf5=1.10.1
  - html5lib=1.0.1
  - hypothesis=3.56.5
  - icu=58.2
  - idna=2.6
  - impactutils=0.8.2
  - infinity=1.4
  - intervals=0.8.1
  - ipykernel=4.8.2
  - ipython=6.3.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.2.1
  - jdcal=1.4
  - jedi=0.12.0
  - jinja2=2.10
  - jmespath=0.9.3
  - jpeg=9b
  - json-c=0.12.1
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - kealib=1.4.7
  - krb5=1.14.6
  - libdap4=3.18.3
  - libffi=3.2.1
  - libiconv=1.15
  - libnetcdf=4.4.1.1
  - libpng=1.6.28
  - libpq=9.6.3
  - libsodium=1.0.16
  - libspatialindex=1.8.5
  - libspatialite=4.3.0a
  - libssh2=1.8.0
  - libtiff=4.0.9
  - libxml2=2.9.8
  - libxslt=1.1.32
  - lxml=4.2.1
  - lzo=2.10
  - mapio=0.7.6
  - markupsafe=1.0
  - matplotlib=2.0.0b3
  - mccabe=0.6.1
  - mistune=0.8.3
  - mock=2.0.0
  - more-itertools=4.1.0
  - munch=2.3.2
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=5.9
  - nose=1.3.7
  - notebook=5.4.1
  - numexpr=2.6.5
  - numpy=1.11.3
  - olefile=0.45.1
  - openblas=0.2.20
  - openjpeg=2.1.2
  - openpyxl=2.5.3
  - openquake.engine=2.9.0
  - openssl=1.0.2o
  - orderedmultidict=0.7.11
  - owslib=0.16.0
  - pandas=0.22.0
  - pandoc=2.2
  - pandocfilters=1.4.2
  - paramiko=2.4.1
  - parso=0.2.0
  - passlib=1.7.1
  - pbr=4.0.2
  - pcre=8.41
  - pexpect=4.5.0
  - phonenumbers=8.9.5
  - pickleshare=0.7.4
  - pillow=4.0.0
  - pip=9.0.3
  - pluggy=0.6.0
  - proj4=4.9.3
  - prompt_toolkit=1.0.15
  - psutil=5.4.5
  - ptyprocess=0.5.2
  - py=1.5.3
  - pyasn1=0.4.2
  - pycodestyle=2.3.1
  - pycparser=2.18
  - pycrypto=2.6.1
  - pyepsg=0.3.2
  - pyflakes=1.6.0
  - pygments=2.2.0
  - pynacl=1.1.2
  - pyopenssl=17.5.0
  - pyparsing=2.2.0
  - pyproj=1.9.5.1
  - pyqt=4.11.4
  - pyshp=1.2.12
  - pysocks=1.6.8
  - pytables=3.4.3
  - pytest=3.5.1
  - pytest-cov=2.5.1
  - pytest-mpl=0.9
  - python=3.5.4
  - python-dateutil=2.7.2
  - pytz=2018.4
  - pyyaml=3.12
  - pyzmq=17.0.0
  - qtconsole=4.3.1
  - rasterio=0.36.0
  - readline=6.2
  - requests=2.18.4
  - rtree=0.8.3
  - s3transfer=0.1.13
  - scipy=1.1.0
  - send2trash=1.5.0
  - setuptools=39.1.0
  - shapely=1.6.4
  - simplegeneric=0.8.1
  - sip=4.18
  - six=1.11.0
  - snuggs=1.4.1
  - sqlalchemy=1.2.7
  - sqlalchemy-utils=0.33.3
  - sqlite=3.13.0
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.5.19
  - tornado=5.0.2
  - traitlets=4.3.2
  - urllib3=1.22
  - wcwidth=0.1.7
  - webencodings=0.5
  - wheel=0.31.0
  - widgetsnbextension=3.2.1
  - xerces-c=3.2.0
  - xlrd=1.1.0
  - xlwt=1.3.0
  - xz=5.2.3
  - yaml=0.1.7
  - zeromq=4.2.5
  - zlib=1.2.11
  - bcrypt=3.1.4
  - libgcc-ng=7.2.0
  - libgfortran=3.0.0
  - qt=4.8.7
  - util-linux=2.21
